### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by KarjalaisenSami** [GispoCoding/NLSgpkgloader#5]
Hello,
I tried to start the plugin, but I get this Python error. QGIS 3.12.

![image](https://user-images.githubusercontent.com/70642642/91980766-75df4100-ed30-11ea-86ac-464c76bd6fe5.png)

**Comment by mvaaltola** [comment]
The error is a ParseError raised by the Python XML parser library. It seems something went wrong with getting the product types from the NLS service. It's hard to say the exact reason for this, most likely it's due to an invalid API key or a network issue. It's not something the plugin can affect. The request it makes is `https://tiedostopalvelu.maanmittauslaitos.fi/tp/feed/mtp?api_key=<your_api_key_here>` which should return a valid xml document. You can try it in your browser to see if it works.

In any case, the a more helpful error message should be provided. I'll create a new issue for this.
